{% set version = "1.6" %}

package:
  name: blinker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blinker/blinker-{{ version }}.tar.gz
  sha256: 5874afe21df4bae8885d31a0a6c4b5861910a575eae6176f051fbb9a6571481b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python =2.7|>=3.5
    - pip
  run:
    - python =2.7|>=3.5

test:
  imports:
    - blinker
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pallets-eco/blinker
  license: MIT
  license_file: LICENSE.rst
  summary: Fast, simple object-to-object and broadcast signaling

extra:
  recipe-maintainers:
    - ocefpaf
    - frol
    - synapticarbors
