{% set version = "1.6.2" %}

package:
  name: blinker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/blinker/blinker-{{ version }}.tar.gz
  sha256: 4afd3de66ef3a9f8067559fb7a1cbe555c17dcbe15971b05d1b625c3e7abe213

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - typing_extensions >=4.2

test:
  imports:
    - blinker
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/pallets-eco/blinker
  license: MIT
  license_file: LICENSE.rst
  summary: Fast, simple object-to-object and broadcast signaling

extra:
  recipe-maintainers:
    - ocefpaf
    - frol
    - synapticarbors
