travis:
  secure:
    BINSTAR_TOKEN: bGxISNAfXuq/aBNLeFKXRBLZgSq99QL7qGo+DTHP/u6Y0q4wKhuN4gHi/LJODDbNGWzFD9kCYm/ZEkvEnpxhSu8Hod2EDKPOtYoX6D99ztTX1iA5j3Z4OBEsAas19wZOZauHxt5Meco/CSwvMiac7dB9pD1ScrAw35gRcc4Q7ypeOwgXcv7WV9AOo7RP9lKxNuFgflzoMDbr87/YLy20BSZNaMUI/iq2RiR/PIcYGiYicoNL6/2e1E0gMPibxSgDh0dMKfeiQoC27CDnYP53Era3JgcpL16qeY9tuzpPLB4faBdbo5OQ6y1FItqJ3DAsORU3gc/fNaNPolcNtkTCv1cPTnBX2StZkM92hJFzkSSwseTeiEdwI76i7Od/GUq+oqWSdQhcsCivwIEajsaY4vTx0Xig3tV/HMP1kGKzdoxt0bt2X89G8W8XQsdx7dBe3RYA5Tm86NhoUdllA42v//9J4XJJ5wJGtf7zIQ9LdTIKRHOONylJcFkm/Gzwyte8srG3hPR5Em3KLuVcLbnFFDpbxgYcimcmq3hrviY/Usctmo7iIhglTGxxmYmCJbneDKdr31jlSDRzkYpYZOVG+JK3IsOFr1JfB4kfx87zarNr8lDDi7ZLNB4dEk/d6oo/q+smC2OwFV2PbhXy4UkZHxPnRSbgBxH+blzouoYGnxs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
